variables:
  USE_FLAKE: "false"
  PKG_COVERAGE: "scpiml"

include:
  - project: karabo/gitlabci
    file: .python-ci.yml
    ref: main
  - project: karabo/gitlabci
    file: .python-package.yml
    ref: main
  - project: karabo/gitlabci
    file: .mirror-device.yml
    ref: main
